name: CI

on: [push]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
        
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: NuGet Restore
        run: dotnet restore $Env:GITHUB_WORKSPACE\Elevens.sln          
                           
      - name: Build
        run: dotnet build $Env:GITHUB_WORKSPACE\Elevens.sln
           
      - name: Run Tests
        run: dotnet test $Env:GITHUB_WORKSPACE\Elevens.sln
