name: CI

on: 
  push:
  pull_request:

env:
  SOLUTION_FILE: $Env:GITHUB_WORKSPACE\Elevens.sln

jobs:
  build:
    runs-on: [windows-latest]
    
    # Skip push builds when the commit is part of an open PR
    if: github.event_name == 'pull_request' || github.event.pull_request == null
    
    steps:
        
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: NuGet Restore
        run: dotnet restore $SOLUTION_FILE
                           
      - name: Build
        run: dotnet build $SOLUTION_FILE
           
      - name: Run Tests
        run: dotnet test -v n $SOLUTION_FILE

